dataset_path: /path/to/your/dataset
model:
  name: resnet50
  out_dim: 128
batch_size: 32 #256 
epochs: 10
lr: 0.001
weight_decay: 1e-6
log_every_n_steps: 10
eval_every_n_epochs: 1
gpu_ids: "0"
fp16_precision: false