dataset_path: "/project/hnguyen2/mvu9/datasets/chexpert/CheXpert-v1.0-small"
batch_size: 128
epochs: 1
eval_every_n_epochs: 1
fine_tune_from: ''
log_every_n_steps: 25
weight_decay: 10e-6
fp16_precision: False
n_gpu: 1
gpu_ids: (0)

model:
  out_dim: 256
  base_model: "vit_base_patch16_224"

dataset:
  s: 1
  input_shape: (224,224,3)
  num_workers: 0
  valid_size: 0.1

loss:
  temperature: 0.5
  use_cosine_similarity: True